### ISSUE TITLE
Creating an Article from local data?

### ISSUE THREAD

**Issue by ramiabraham** [m1x0n/helpscout-docs-api-php#2]
Hello,

Thank you for this library - it's been a huge help.

I'm running into some issues when attempting to create an article.

Within a function, I'm first creating an instance of `DocsApiClient()`, and setting the api key:

`$docsApiClient = new DocsApiClient();`
`$api_key       = 'KEY';`
`$docsApiClient->setKey( $api_key );`

Then, within the context of a `DirectoryIterator` loop, for each file within, I attempt to create an Article object, set the text and category, and initiate the article creation via `$docsApiClient->createArticle()`.

`$article = new Article();`
`$article->setText( file_get_contents( $file ) );`
`$article->setCategories( $categoryId );`
`$docsApiClient->createArticle( $article, $reload = false );`

What am I missing here? Thank again.

**Comment by m1x0n** [comment]
Hi, @ramiabraham. According to Docs hierarchy:

```
Site - Collection - Category
        |              |
     Article        Article
```

You're able to create Article  either inside Category or inside Collection. Also you must be sure that your Collection or Category exists (created by API or web UI).

`setCategories()` method accepts array of category ids. So you should change your code to:

```
$article->setCategories( array($categoryId) ); // or [$categoryId]
```

Checkout example below:

``` php
<?php

// ... docs Client initialization
$article = new Article();
$article->setCategories(array($category->getId())); // array of ids
$article->setText("Hi there!");
$article->setName(uniqid("Category article"));
$article->setStatus('published'); //unpublished by default
$created = $docsClient->createArticle($article, true); // returns created article
```

Let me know if you have any questions.

**Comment by ramiabraham** [comment]
Thanks @m1x0n - this got me further :)

I keep getting the exception defined in `DocsApiClient.php:133`:

`Uncaught HelpScoutDocs\ApiException: The request was not formatted correctly in /.../api/src/HelpScoutDocs/DocsApiClient.php:133
Stack trace:
#0 /.../api/src/HelpScoutDocs/DocsApiClient.php(324): HelpScoutDocs\DocsApiClient->checkStatus(400, 'POST', Array)
#1 /.../api/src/HelpScoutDocs/DocsApiClient.php(763): HelpScoutDocs\DocsApiClient->doPostFile('articles/upload', Array, 200)
#2 /.../helpscout.php(104): HelpScoutDocs\DocsApiClient->uploadArticle('572a32d7c697917...', '/root/path...', '1292', 'filename...', 'filename-slug...', 'POST', true)
#3 /.../helpscout.php(121): uploadToHelpscout()
#4 {main}
  thrown in /.../api/src/HelpScoutDocs/DocsApiClient.php on line 133`

...even though everything appears ok otherwise (`doPostFile()` returns `200`, api key is defined, basic curl auth goes ok).

I also tried the `uploadArticle()` method, which ultimately runs into the exact same error.

Have you encountered this?

**Comment by m1x0n** [comment]
@ramiabraham, I'm going to fix this in upcoming release.

**Comment by ramiabraham** [comment]
@m1x0n Ah ok cool, thanks for the update. Please let me know if I can help with testing or anything at all.

**Comment by m1x0n** [comment]
@ramiabraham, I've released new version. Could you please give it a try. I'll appreciate your feed back.

**Comment by ramiabraham** [comment]
Hey @m1x0n,

Very sorry for the absurdly late reply.

I was never able to get any part of it to work, either via uploadArticle _or_ createArticle. Have you tried it in cases where you have a local markdown file, or json data that you'd like to either create an article from, or upload the markdown file?

Presently, I still get the `The request was not formatted correctly` error, despite everything being specified (I think) correctly.

**Comment by m1x0n** [comment]
@ramiabraham, Have you tried latest version and [this](https://github.com/m1x0n/helpscout-docs-api-php/blob/master/examples/upload-article.php) example?
According to the official documentation it should automatically detect markdown.

**Comment by ramiabraham** [comment]
@m1x0n I have yes - even hard-coding values directly into this library all result in the `The request was not formatted correctly` error.
